CREATE OR REPLACE PACKAGE PKG_MAXSALUD IS

--VARIABLES PUBLICAS
V_MONTO_MULTA        PAGO_MOROSO.MONTO_MULTA%TYPE := 0;
V_PORC_DESCTO_3EDAD  PORC_DESCTO_3RA_EDAD.PORCENTAJE_DESCTO%TYPE := 0;

/*FUNCION QUE RETORNA EL VALOR DE DESCUENTO PARA CLIENTES MAYORES A 70*/
FUNCTION FN_OBT_DESCTO_MULTA70(P_MULTA NUMBER,P_EDAD NUMBER) RETURN NUMBER;

END PKG_MAXSALUD;


CREATE OR REPLACE PACKAGE BODY PKG_MAXSALUD IS
    
    FUNCTION FN_OBT_DESCTO_MULTA70(P_MULTA NUMBER,P_EDAD NUMBER) RETURN NUMBER
    IS
    V_DESCTO_70 NUMBER(6);
    BEGIN
        
        IF P_EDAD > 70 THEN
            
            SELECT PORCENTAJE_DESCTO
            INTO PKG_MAXSALUD.V_PORC_DESCTO_3EDAD
            FROM PORC_DESCTO_3RA_EDAD
            WHERE P_EDAD BETWEEN ANNO_INI AND ANNO_TER;
            
            V_DESCTO_70:= TRUNC(P_MULTA*(PKG_MAXSALUD.V_PORC_DESCTO_3EDAD/100));
            RETURN V_DESCTO_70;
            
        ELSE
            RETURN 0;
        END IF;
        
    END FN_OBT_DESCTO_MULTA70;

END PKG_MAXSALUD;
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION FN_OBT_NOMBRE_ESPECIALIDAD(P_ATE_ID NUMBER) RETURN VARCHAR2
IS
V_NOMBRE_ESPECIALDAD VARCHAR2(25) ;
BEGIN
    SELECT E.NOMBRE
    INTO V_NOMBRE_ESPECIALDAD
    FROM ATENCION A
                   JOIN MEDICO M ON A.MED_RUN = M.MED_RUN
                   JOIN ESPECIALIDAD E ON M.ESP_ID = E.ESP_ID
                   AND A.ATE_ID = P_ATE_ID;
    RETURN V_NOMBRE_ESPECIALDAD;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    RETURN ' ';
END FN_OBT_NOMBRE_ESPECIALIDAD;
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ATENCION_MOROSOS(P_ANNO_PROCESO NUMBER)
IS
    CURSOR C_MOROSOS IS
    SELECT P.PAC_RUN,
           P.DV_RUN,
           P.PNOMBRE||' '||P.SNOMBRE||' '||P.APATERNO||' '||P.AMATERNO AS PAC_NOMBRE,
           TRUNC(MONTHS_BETWEEN(SYSDATE,P.FECHA_NACIMIENTO)/12) AS PAC_EDAD,
           A.ATE_ID,
           PA.FECHA_VENC_PAGO,
           PA.FECHA_PAGO,
           PA.FECHA_PAGO-PA.FECHA_VENC_PAGO AS DIAS_MOROSIDAD,
           A.COSTO AS COSTO_ATENCION
    FROM PACIENTE P
                   JOIN ATENCION A ON P.PAC_RUN = A.PAC_RUN
                   JOIN PAGO_ATENCION PA ON A.ATE_ID = PA.ATE_ID
    WHERE PA.FECHA_PAGO > PA.FECHA_VENC_PAGO AND EXTRACT(YEAR FROM PA.FECHA_PAGO) = P_ANNO_PROCESO-1
    ORDER BY 5,P.APATERNO;
    
    R_PAGO_MOROSO PAGO_MOROSO%ROWTYPE;
    
    TYPE TYPE_REGISTRO_MULTA IS RECORD
    (MULTA1 NUMBER(4):= 1200,
     MULTA2 NUMBER(4):= 1300,
     MULTA3 NUMBER(4):= 1700,
     MULTA4 NUMBER(4):= 1900,
     MULTA5 NUMBER(4):= 1100,
     MULTA6 NUMBER(4):= 2000,
     MULTA7 NUMBER(4):= 2300);
     REG_M_VALOR TYPE_REGISTRO_MULTA;
     
     V_VALOR_DESCUENTO70 NUMBER(6);
    
    
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PAGO_MOROSO';
    FOR  R_MOROSOS IN C_MOROSOS LOOP
        
        R_PAGO_MOROSO.PAC_RUN := R_MOROSOS.PAC_RUN;
        R_PAGO_MOROSO.PAC_DV_RUN := R_MOROSOS.DV_RUN;
        R_PAGO_MOROSO.PAC_NOMBRE := R_MOROSOS.PAC_NOMBRE;
        R_PAGO_MOROSO.ATE_ID := R_MOROSOS.ATE_ID;
        R_PAGO_MOROSO.FECHA_VENC_PAGO := R_MOROSOS.FECHA_VENC_PAGO;
        R_PAGO_MOROSO.FECHA_PAGO := R_MOROSOS.FECHA_PAGO;
        R_PAGO_MOROSO.DIAS_MOROSIDAD := R_MOROSOS.DIAS_MOROSIDAD;
        R_PAGO_MOROSO.ESPECIALIDAD_ATENCION := FN_OBT_NOMBRE_ESPECIALIDAD(R_MOROSOS.ATE_ID);
        R_PAGO_MOROSO.COSTO_ATENCION := R_MOROSOS.COSTO_ATENCION;
        
        IF R_PAGO_MOROSO.ESPECIALIDAD_ATENCION = 'Medicina General' THEN
            R_PAGO_MOROSO.MONTO_MULTA := R_MOROSOS.DIAS_MOROSIDAD*REG_M_VALOR.MULTA1;
        ELSIF R_PAGO_MOROSO.ESPECIALIDAD_ATENCION = 'Traumatologia' THEN
            R_PAGO_MOROSO.MONTO_MULTA := R_MOROSOS.DIAS_MOROSIDAD*REG_M_VALOR.MULTA2;
        ELSIF R_PAGO_MOROSO.ESPECIALIDAD_ATENCION IN ('Neurologia','Pediatria') THEN
            R_PAGO_MOROSO.MONTO_MULTA := R_MOROSOS.DIAS_MOROSIDAD*REG_M_VALOR.MULTA3;
        ELSIF R_PAGO_MOROSO.ESPECIALIDAD_ATENCION = 'Oftalmologia' THEN
            R_PAGO_MOROSO.MONTO_MULTA := R_MOROSOS.DIAS_MOROSIDAD*REG_M_VALOR.MULTA4;
        ELSIF R_PAGO_MOROSO.ESPECIALIDAD_ATENCION = 'Geriatria' THEN
            R_PAGO_MOROSO.MONTO_MULTA := R_MOROSOS.DIAS_MOROSIDAD*REG_M_VALOR.MULTA5;
        ELSIF R_PAGO_MOROSO.ESPECIALIDAD_ATENCION IN ('Ginecologia','Gastroenterologia') THEN
            R_PAGO_MOROSO.MONTO_MULTA := R_MOROSOS.DIAS_MOROSIDAD*REG_M_VALOR.MULTA6;
        ELSIF R_PAGO_MOROSO.ESPECIALIDAD_ATENCION = 'Dermatologia' THEN
            R_PAGO_MOROSO.MONTO_MULTA := R_MOROSOS.DIAS_MOROSIDAD*REG_M_VALOR.MULTA7;    
        END IF;
        
        V_VALOR_DESCUENTO70 := PKG_MAXSALUD.FN_OBT_DESCTO_MULTA70(R_PAGO_MOROSO.MONTO_MULTA,R_MOROSOS.PAC_EDAD);
        
        R_PAGO_MOROSO.MONTO_MULTA := R_PAGO_MOROSO.MONTO_MULTA - V_VALOR_DESCUENTO70;
        
        IF R_MOROSOS.PAC_EDAD >70 THEN
            R_PAGO_MOROSO.OBSERVACION := 'Paciente tenia '||R_MOROSOS.PAC_EDAD||'. Se aplicó descuento paciente  amyor a 70 años';
        ELSE
            R_PAGO_MOROSO.OBSERVACION := NULL;
        END IF;
        
        INSERT INTO PAGO_MOROSO VALUES R_PAGO_MOROSO;
    END LOOP;
    
END SP_ATENCION_MOROSOS;
/


SELECT * FROM PAGO_MOROSO;
SELECT ATE_ID, FN_OBT_NOMBRE_ESPECIALIDAD(ATE_ID)
FROM ATENCION;
EXEC SP_ATENCION_MOROSOS(2021);