/*CASO 2*/

--BIND
VAR B_TRAMO_1 NUMBER;
EXEC :B_TRAMO_1 := 1000001;
VAR B_TRAMO_2 NUMBER;
EXEC :B_TRAMO_2 := 3000000;
VAR B_TRAMO_3 NUMBER;
EXEC :B_TRAMO_3 := 3000001;
VAR B_TRAMO_4 NUMBER;
EXEC :B_TRAMO_4 := 6000000;

DECLARE

    TYPE TIPO_REG_PESOS IS RECORD
    (PESO_NORMAL NUMBER(4) := 1200,
    PESO_EXTRA1 NUMBER(3) := 300,
    PESO_EXTRA2 NUMBER(3) := 550,
    PESO_EXTRA3 NUMBER(3) := 700);
    
    REG_PESOS TIPO_REG_PESOS;
    
    R_CLIENTE_TODOSUMA CLIENTE_TODOSUMA%ROWTYPE;
    
    CURSOR CUR_CLIENTES IS
    SELECT
            C.NRO_CLIENTE AS NRO_CLIENTE,
            TO_CHAR(C.NUMRUN,'09G999G999')||'-'||UPPER(C.DVRUN) AS RUT_CLIENTE,
            C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO AS NOMBRE_CLIENTE,
            TP.NOMBRE_TIPO_CLIENTE AS TIPO_CLIENTE,
            SUM(CC.MONTO_SOLICITADO) AS MONTO_SOLIC_CLIENTE
    FROM  CLIENTE C
                    JOIN TIPO_CLIENTE TP ON C.COD_TIPO_CLIENTE = TP.COD_TIPO_CLIENTE
                    JOIN CREDITO_CLIENTE CC ON C.NRO_CLIENTE = CC.NRO_CLIENTE
    WHERE EXTRACT(YEAR FROM FECHA_SOLIC_CRED) = EXTRACT(YEAR FROM SYSDATE) -1
    GROUP BY C.NRO_CLIENTE, TO_CHAR(C.NUMRUN,'09G999G999')||'-'||UPPER(C.DVRUN),
    C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO, TP.NOMBRE_TIPO_CLIENTE
    order by 1
    ;

BEGIN
    
    FOR R_CLIENTES IN CUR_CLIENTES LOOP
        
        R_CLIENTE_TODOSUMA.NRO_CLIENTE := R_CLIENTES.NRO_CLIENTE;
        R_CLIENTE_TODOSUMA.RUN_CLIENTE := R_CLIENTES.RUT_CLIENTE;
        R_CLIENTE_TODOSUMA.NOMBRE_CLIENTE := R_CLIENTES.NOMBRE_CLIENTE;
        R_CLIENTE_TODOSUMA.TIPO_CLIENTE := R_CLIENTES.TIPO_CLIENTE;
        R_CLIENTE_TODOSUMA.MONTO_SOLIC_CREDITOS := R_CLIENTES.MONTO_SOLIC_CLIENTE;
        
        IF R_CLIENTE_TODOSUMA.MONTO_SOLIC_CREDITOS BETWEEN :B_TRAMO_1 AND :B_TRAMO_2 THEN
            R_CLIENTE_TODOSUMA.MONTO_PESOS_TODOSUMA := (R_CLIENTE_TODOSUMA.MONTO_SOLIC_CREDITOS/100000)*(REG_PESOS.PESO_EXTRA1+REG_PESOS.PESO_NORMAL);
        ELSIF R_CLIENTE_TODOSUMA.MONTO_SOLIC_CREDITOS BETWEEN :B_TRAMO_3 AND :B_TRAMO_4 THEN
            R_CLIENTE_TODOSUMA.MONTO_PESOS_TODOSUMA := (R_CLIENTE_TODOSUMA.MONTO_SOLIC_CREDITOS/100000)*(REG_PESOS.PESO_EXTRA2+REG_PESOS.PESO_NORMAL);
        ELSE
            R_CLIENTE_TODOSUMA.MONTO_PESOS_TODOSUMA := (R_CLIENTE_TODOSUMA.MONTO_SOLIC_CREDITOS/100000)*(REG_PESOS.PESO_EXTRA3+REG_PESOS.PESO_NORMAL);
        END IF;
        
        INSERT INTO CLIENTE_TODOSUMA VALUES R_CLIENTE_TODOSUMA;
        COMMIT;
    END LOOP;
END;