--CASO 3

/*----------------------------------------------------------------------------------------------------------
                |NOMBRE|               |NUMERO DE SOLICITUD DE CREDITO|   |CANTIDAD CUOTAS A POSTERGAR|

SEBASTIAN PATRICIO QUINTANA BERRIOS                  2001                                 2
KAREN SOFIA PRADENAS MANDIOLA                        3004                                 1
JULIAN PAUL ARRIAGADA LUJAN                          2004                                 1
-----------------------------------------------------------------------------------------------------------*/


--BIND
VAR B_NRO_CLIENTE NUMBER;
EXEC :B_NRO_CLIENTE := 5;

VAR B_NRO_SOLIC_CRED NUMBER;
EXEC :B_NRO_SOLIC_CRED := 2001;

VAR B_CANT_CUOTAS_POST NUMBER;
EXEC :B_CANT_CUOTAS_POST := 2;

DECLARE
V_NRO_CUOTA       CUOTA_CREDITO_CLIENTE.NRO_CUOTA%TYPE;
V_FECHA_VENC      CUOTA_CREDITO_CLIENTE.FECHA_VENC_CUOTA%TYPE;
V_VALOR_CUOTA     CUOTA_CREDITO_CLIENTE.VALOR_CUOTA%TYPE;
V_FECHA_PAGO      CUOTA_CREDITO_CLIENTE.FECHA_PAGO_CUOTA%TYPE;
V_MONTO_PAGADO    CUOTA_CREDITO_CLIENTE.MONTO_PAGADO%TYPE;
V_SALDO_POR_PAGAR CUOTA_CREDITO_CLIENTE.SALDO_POR_PAGAR%TYPE;
V_COD_FORMA_PAGO  CUOTA_CREDITO_CLIENTE.COD_FORMA_PAGO%TYPE;

V_TIPO_CREDITO            CREDITO.NOMBRE_CREDITO%TYPE;
V_NRO_CUOTAS_PEDIDAS      NUMBER(3);

V_NRO_ULTIMA_CUOTA    CUOTA_CREDITO_CLIENTE.NRO_CUOTA%TYPE;
V_FECHA_ULTIMA_CUOTA  CUOTA_CREDITO_CLIENTE.FECHA_VENC_CUOTA%TYPE;
V_VALOR_ULTIMA_CUOTA  CUOTA_CREDITO_CLIENTE.VALOR_CUOTA%TYPE;

BEGIN

    --TIPO DE CREDITO QUE PIDIO EL CLIENTE SEGUN EL NRO DE SOLICITUD
    SELECT 
        CR.NOMBRE_CREDITO 
    INTO V_TIPO_CREDITO       
    FROM CLIENTE C
                JOIN CREDITO_CLIENTE CC ON C.NRO_CLIENTE = CC.NRO_CLIENTE
                JOIN CREDITO CR ON CC.COD_CREDITO = CR.COD_CREDITO
                JOIN CUOTA_CREDITO_CLIENTE CCC ON CC.NRO_SOLIC_CREDITO = CCC.NRO_SOLIC_CREDITO
    WHERE CC.NRO_SOLIC_CREDITO = :B_NRO_SOLIC_CRED AND C.NRO_CLIENTE = :B_NRO_CLIENTE
    ;
    
    --CANTIDAD DE CUOTAS QUE PIDIO EL CLIENTE EL AÑO PASADO
    SELECT COUNT(*)
    INTO V_NRO_CUOTAS_PEDIDAS
    FROM CREDITO_CLIENTE
    WHERE NRO_CLIENTE = :B_NRO_CLIENTE AND EXTRACT(YEAR FROM FECHA_SOLIC_CRED) = EXTRACT(YEAR FROM SYSDATE)-1
    ;
    
    --ULTIMA CUOTA, ULTIMA FECHA DE ESA CUOTA Y SU VALOR
    SELECT MAX(NRO_CUOTA),MAX(FECHA_VENC_CUOTA),VALOR_CUOTA
    INTO V_NRO_ULTIMA_CUOTA,V_FECHA_ULTIMA_CUOTA, V_VALOR_ULTIMA_CUOTA
    FROM CUOTA_CREDITO_CLIENTE
    WHERE NRO_SOLIC_CREDITO = :B_NRO_SOLIC_CRED
    GROUP BY VALOR_CUOTA;
    
    V_FECHA_PAGO:=NULL;
    V_COD_FORMA_PAGO:=NULL;
    V_SALDO_POR_PAGAR:=NULL;
    V_MONTO_PAGADO:=NULL;
    
    IF V_TIPO_CREDITO = 'Crédito Hipotecario' THEN
        IF :B_CANT_CUOTAS_POST = 1 THEN
            V_NRO_CUOTA:=V_NRO_ULTIMA_CUOTA+1;
            V_FECHA_VENC := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
            V_VALOR_CUOTA := V_VALOR_ULTIMA_CUOTA;
            INSERT INTO CUOTA_CREDITO_CLIENTE
            VALUES (:B_NRO_SOLIC_CRED,V_NRO_CUOTA,V_FECHA_VENC,V_VALOR_CUOTA,V_FECHA_PAGO,V_MONTO_PAGADO,V_SALDO_POR_PAGAR,V_COD_FORMA_PAGO);

            
        ELSIF :B_CANT_CUOTAS_POST = 2 THEN
            V_NRO_CUOTA:=V_NRO_ULTIMA_CUOTA+1;
            V_FECHA_VENC := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
            V_VALOR_CUOTA := V_VALOR_ULTIMA_CUOTA*1.005;
            
            INSERT INTO CUOTA_CREDITO_CLIENTE
            VALUES (:B_NRO_SOLIC_CRED,V_NRO_CUOTA,V_FECHA_VENC,V_VALOR_CUOTA,V_FECHA_PAGO,V_MONTO_PAGADO,V_SALDO_POR_PAGAR,V_COD_FORMA_PAGO);
            
            V_NRO_CUOTA:=V_NRO_ULTIMA_CUOTA+2;
            V_FECHA_VENC := ADD_MONTHS(V_FECHA_VENC,1);
            
            
            INSERT INTO CUOTA_CREDITO_CLIENTE
            VALUES (:B_NRO_SOLIC_CRED,V_NRO_CUOTA,V_FECHA_VENC,V_VALOR_CUOTA,V_FECHA_PAGO,V_MONTO_PAGADO,V_SALDO_POR_PAGAR,V_COD_FORMA_PAGO);
        END IF;
        
       
    ELSIF V_TIPO_CREDITO = 'Crédito de Consumo' THEN
        IF :B_CANT_CUOTAS_POST = 1 THEN
            V_NRO_CUOTA:=V_NRO_ULTIMA_CUOTA+1;
            V_FECHA_VENC := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
            V_VALOR_CUOTA := V_VALOR_ULTIMA_CUOTA*1.01;
            
            INSERT INTO CUOTA_CREDITO_CLIENTE
            VALUES (:B_NRO_SOLIC_CRED,V_NRO_CUOTA,V_FECHA_VENC,V_VALOR_CUOTA,V_FECHA_PAGO,V_MONTO_PAGADO,V_SALDO_POR_PAGAR,V_COD_FORMA_PAGO);

        END IF;
        
    ELSIF V_TIPO_CREDITO = 'Crédito Automotriz' THEN
        IF :B_CANT_CUOTAS_POST = 1 THEN
            V_NRO_CUOTA:=V_NRO_ULTIMA_CUOTA+1;
            V_FECHA_VENC := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
            V_VALOR_CUOTA := V_VALOR_ULTIMA_CUOTA*1.02;
            
            INSERT INTO CUOTA_CREDITO_CLIENTE
            VALUES (:B_NRO_SOLIC_CRED,V_NRO_CUOTA,V_FECHA_VENC,V_VALOR_CUOTA,V_FECHA_PAGO,V_MONTO_PAGADO,V_SALDO_POR_PAGAR,V_COD_FORMA_PAGO);
        END IF;
    
    END IF;
END
;

/
SELECT * FROM CUOTA_CREDITO_CLIENTE
WHERE NRO_SOLIC_CREDITO = 2001;
