--CASO 1

--BIND
VAR B_RUN_EMP NUMBER;
EXEC :B_RUN_EMP := 11846972;

VAR B_ANNO_PROCESO NUMBER;
EXEC :B_ANNO_PROCESO := 2021;

VAR B_COMUNA1 VARCHAR2;
EXEC :B_COMUNA1 := 'María Pinto';

VAR B_COMUNA2 VARCHAR2;
EXEC :B_COMUNA2 := 'Curacaví';

VAR B_COMUNA3 VARCHAR2;
EXEC :B_COMUNA3 := 'Talagante';

VAR B_COMUNA4 VARCHAR2;
EXEC :B_COMUNA4 := 'El Monte';

VAR B_COMUNA5 VARCHAR2;
EXEC :B_COMUNA5 := 'Buin';

VAR B_VALOR_MOV1 NUMBER;
EXEC :B_VALOR_MOV1 := 20000;

VAR B_VALOR_MOV2 NUMBER;
EXEC :B_VALOR_MOV2 := 25000;

VAR B_VALOR_MOV3 NUMBER;
EXEC :B_VALOR_MOV3 := 30000;

VAR B_VALOR_MOV4 NUMBER;
EXEC :B_VALOR_MOV4 := 35000;

VAR B_VALOR_MOV5 NUMBER;
EXEC :B_VALOR_MOV5 := 40000;

DECLARE

V_DVRUN EMPLEADO.DVRUN_EMP%TYPE;
V_NOMBRE_EMP VARCHAR2(50);
V_SUELDO EMPLEADO.SUELDO_BASE%TYPE;
V_PORC_MOV1 NUMBER(3);
V_VALOR_MOV1 EMPLEADO.SUELDO_BASE%TYPE;
V_VALOR_MOV2 EMPLEADO.SUELDO_BASE%TYPE;
V_TOTAL_MOV EMPLEADO.SUELDO_BASE%TYPE;

BEGIN
SELECT
        E.DVRUN_EMP,
        E.SNOMBRE_EMP||' '||E.PNOMBRE_EMP||' '||E.APPATERNO_EMP||' '||E.APMATERNO_EMP,
        E.SUELDO_BASE,
        TRUNC(E.SUELDO_BASE/100000),
        ROUND(E.SUELDO_BASE*TRUNC(E.SUELDO_BASE/100000)/100),
        
        CASE
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA1 THEN :B_VALOR_MOV1
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA2 THEN :B_VALOR_MOV2
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA3 THEN :B_VALOR_MOV3
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA4 THEN :B_VALOR_MOV4
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA5 THEN :B_VALOR_MOV5
            ELSE 0
        END,
        
        ROUND(E.SUELDO_BASE*TRUNC(E.SUELDO_BASE/100000)/100) +
        CASE
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA1 THEN :B_VALOR_MOV1
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA2 THEN :B_VALOR_MOV2
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA3 THEN :B_VALOR_MOV3
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA4 THEN :B_VALOR_MOV4
            WHEN CO.NOMBRE_COMUNA = :B_COMUNA5 THEN :B_VALOR_MOV5
            ELSE 0
        END
        
INTO V_DVRUN,V_NOMBRE_EMP,V_SUELDO,V_PORC_MOV1,V_VALOR_MOV1,V_VALOR_MOV2,V_TOTAL_MOV
FROM EMPLEADO E
                JOIN COMUNA CO ON E.ID_COMUNA = CO.ID_COMUNA
WHERE NUMRUN_EMP = :B_RUN_EMP
;

INSERT INTO PROY_MOVILIZACION VALUES(:B_ANNO_PROCESO,:B_RUN_EMP,V_DVRUN,V_NOMBRE_EMP,V_SUELDO,V_PORC_MOV1,V_VALOR_MOV1,V_VALOR_MOV2,V_TOTAL_MOV);

END
;