

DECLARE

    --REGISTRO CON LOS DESTINOS DE LOS MEDICOS
    TYPE TIPO_REG_DESTINO IS RECORD
    (DESTINO_1 VARCHAR(50):= 'Servicio de Atención Primaria de Urgencia (SAPU)',
    DESTINO_2 VARCHAR(50):= 'Hospitales del área de la Salud Pública',
    DESTINO_3 VARCHAR(50):= 'Centros de Salud Familiar (CESFAM)');
    REG_DESTINO TIPO_REG_DESTINO;
    
    R_MED_COMUNIDAD     MEDICO_SERVICIO_COMUNIDAD%ROWTYPE;

    CURSOR C_MEDICOS IS
    SELECT U.NOMBRE AS NOMBRE,
        TO_CHAR(M.MED_RUN,'09G999G999')||'-'||M.DV_RUN AS RUN_MED, 
        M.PNOMBRE||' '||M.SNOMBRE||' '||M.APATERNO||' '||M.AMATERNO AS MEDICO,
        SUBSTR(U.NOMBRE,1,2)||SUBSTR(M.PNOMBRE,-3,2)||'@medicoktk.cl' AS CORREO,
        COUNT(A.ATE_ID) AS ATENCIONES_MED
    FROM MEDICO M 
    JOIN UNIDAD U ON M.UNI_ID = U.UNI_ID
    LEFT JOIN ATENCION A ON A.MED_RUN = M.MED_RUN AND EXTRACT(YEAR FROM A.FECHA_ATENCION) = EXTRACT(YEAR FROM SYSDATE)-1
    GROUP BY U.NOMBRE,
            TO_CHAR(M.MED_RUN,'09G999G999')||'-'||M.DV_RUN, 
            M.PNOMBRE||' '||M.SNOMBRE||' '||M.APATERNO||' '||M.AMATERNO,
            SUBSTR(U.NOMBRE,1,2)||SUBSTR(M.PNOMBRE,-3,2)||'@medicoktk.cl', M.APATERNO
    HAVING COUNT(A.ATE_ID)<(SELECT MAX(COUNT(A.ATE_ID))
                            FROM MEDICO M 
                            JOIN UNIDAD U ON M.UNI_ID = U.UNI_ID
                            LEFT JOIN ATENCION A ON A.MED_RUN = M.MED_RUN AND EXTRACT(YEAR FROM A.FECHA_ATENCION) = EXTRACT(YEAR FROM SYSDATE)-1
                            GROUP BY U.NOMBRE,
                                    TO_CHAR(M.MED_RUN,'09G999G999')||'-'||M.DV_RUN, 
                                    M.PNOMBRE||' '||M.SNOMBRE||' '||M.APATERNO||' '||M.AMATERNO,
                                    SUBSTR(U.NOMBRE,1,2)||SUBSTR(M.PNOMBRE,-3,2)||'@medicoktk.cl')
    ORDER BY U.NOMBRE, M.APATERNO;
    
    --CREAR REGISTRO DEL CURSOR
    R_MEDICOS C_MEDICOS%ROWTYPE;
    
BEGIN
    OPEN C_MEDICOS;
    LOOP
        FETCH C_MEDICOS INTO R_MEDICOS;
        EXIT WHEN C_MEDICOS%NOTFOUND;
        
        --R_MED_COMUNIDAD.ID_MED_SCOMUN := ISEQ$$_91560.NEXTVAL;
        R_MED_COMUNIDAD.UNIDAD := R_MEDICOS.NOMBRE;
        R_MED_COMUNIDAD.RUN_MEDICO := R_MEDICOS.RUN_MED;
        R_MED_COMUNIDAD.NOMBRE_MEDICO := R_MEDICOS.MEDICO;
        R_MED_COMUNIDAD.CORREO_INSTITUCIONAL := R_MEDICOS.CORREO;
        R_MED_COMUNIDAD.TOTAL_ATEN_MEDICAS := R_MEDICOS.ATENCIONES_MED;
        
        IF R_MEDICOS.NOMBRE = 'ATENCIÓN ADULTO' OR R_MEDICOS.NOMBRE = 'ATENCIÓN AMBULATORIA' THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_1;
        ELSIF R_MEDICOS.NOMBRE = 'ATENCIÓN URGENCIA' AND R_MEDICOS.ATENCIONES_MED BETWEEN 0 AND 3 THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_1;
        ELSIF R_MEDICOS.NOMBRE = 'ATENCIÓN URGENCIA' AND R_MEDICOS.ATENCIONES_MED >3 THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_2;
        ELSIF R_MEDICOS.NOMBRE = 'CARDIOLOGÍA' OR R_MEDICOS.NOMBRE = 'ONCOLÓGICA' THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_2;
        ELSIF (R_MEDICOS.NOMBRE = 'CIRUGÍA' OR R_MEDICOS.NOMBRE = 'CIRUGÍA PLÁSTICA') AND R_MEDICOS.ATENCIONES_MED BETWEEN 0 AND 3 THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_1;
        ELSIF (R_MEDICOS.NOMBRE = 'CIRUGÍA' OR R_MEDICOS.NOMBRE = 'CIRUGÍA PLÁSTICA') AND R_MEDICOS.ATENCIONES_MED > 3 THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_2;
        ELSIF R_MEDICOS.NOMBRE = 'PACIENTE CRÍTICO' THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_2; 
        ELSIF R_MEDICOS.NOMBRE = 'PSIQUIATRÍA Y SALUD MENTAL' THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_3;
        ELSIF R_MEDICOS.NOMBRE = 'TRAUMATOLOGÍA ADULTO' AND R_MEDICOS.ATENCIONES_MED BETWEEN 0 AND 3 THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_1;
        ELSIF R_MEDICOS.NOMBRE = 'TRAUMATOLOGÍA ADULTO' AND R_MEDICOS.ATENCIONES_MED > 3 THEN
            R_MED_COMUNIDAD.DESTINACION := REG_DESTINO.DESTINO_2;
        END IF;
        
        INSERT INTO MEDICO_SERVICIO_COMUNIDAD VALUES R_MED_COMUNIDAD;
        COMMIT;
    END LOOP;
    CLOSE C_MEDICOS;
END;
/







