--CASO 2

--BIND
VAR B_NUMRUN_CLI NUMBER;
EXEC :B_NUMRUN_CLI := 7455786;

VAR B_MONTO_AHORRADO1 NUMBER;
EXEC :B_MONTO_AHORRADO1 := 900000;
VAR B_MONTO_AHORRADO2 NUMBER;
EXEC :B_MONTO_AHORRADO2 := 900001;
VAR B_MONTO_AHORRADO3 NUMBER;
EXEC :B_MONTO_AHORRADO3 := 2000000;
VAR B_MONTO_AHORRADO4 NUMBER;
EXEC :B_MONTO_AHORRADO4 := 2000001;
VAR B_MONTO_AHORRADO5 NUMBER;
EXEC :B_MONTO_AHORRADO5 := 5000000;
VAR B_MONTO_AHORRADO6 NUMBER;
EXEC :B_MONTO_AHORRADO6 := 5000001;
VAR B_MONTO_AHORRADO7 NUMBER;
EXEC :B_MONTO_AHORRADO7 := 8000000;
VAR B_MONTO_AHORRADO8 NUMBER;
EXEC :B_MONTO_AHORRADO8 := 8000001;
VAR B_MONTO_AHORRADO9 NUMBER;
EXEC :B_MONTO_AHORRADO9 := 15000000;

VAR B_MONTO_GIFTCARD1 NUMBER;
EXEC :B_MONTO_GIFTCARD1 :=50000;
VAR B_MONTO_GIFTCARD2 NUMBER;
EXEC :B_MONTO_GIFTCARD2 :=100000;
VAR B_MONTO_GIFTCARD3 NUMBER;
EXEC :B_MONTO_GIFTCARD3 :=200000;
VAR B_MONTO_GIFTCARD4 NUMBER;
EXEC :B_MONTO_GIFTCARD4 :=300000;

DECLARE

V_NRO_CLI           CUMPLEANNO_CLIENTE.NRO_CLIENTE%TYPE;
V_DVRUN_CLI         CLIENTE.DVRUN%TYPE;
V_RUT_CLI           CUMPLEANNO_CLIENTE.RUN_CLIENTE%TYPE;
V_NOMBRE_CLI        CUMPLEANNO_CLIENTE.NOMBRE_CLIENTE%TYPE;
V_PROFESION         CUMPLEANNO_CLIENTE.PROFESION_OFICIO%TYPE;
V_FECHA_CUMPLEANO   CUMPLEANNO_CLIENTE.DIA_CUMPLEANO%TYPE;
V_MONTO_GIFTCARD    CUMPLEANNO_CLIENTE.MONTO_GIFCARD%TYPE;
V_OBSVERVACION      CUMPLEANNO_CLIENTE.OBSERVACION%TYPE;
V_TOTAL_AHORRADO    NUMBER(10);
V_FECHA_CUMPLE      DATE;
BEGIN

    SELECT
            C.NRO_CLIENTE,
            C.DVRUN,
            PNOMBRE||' '||SNOMBRE||' '||APPATERNO||' '||APMATERNO,
            NOMBRE_PROF_OFIC,
            TO_CHAR(FECHA_NACIMIENTO,'DD "de" MONTH'),
            MONTO_TOTAL_AHORRADO,
            
            
            CASE
            WHEN EXTRACT(MONTH FROM FECHA_NACIMIENTO) != EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,1)) THEN 'El cliente no está de cumpleaños en el mes procesado'
            END,
            FECHA_NACIMIENTO
            
            
    INTO V_NRO_CLI,V_DVRUN_CLI,V_NOMBRE_CLI,V_PROFESION,V_FECHA_CUMPLEANO,V_TOTAL_AHORRADO,V_OBSVERVACION,V_FECHA_CUMPLE
    FROM CLIENTE C
                JOIN PROFESION_OFICIO PO ON C.COD_PROF_OFIC = PO.COD_PROF_OFIC
                JOIN PRODUCTO_INVERSION_CLIENTE PR ON C.NRO_CLIENTE = PR.NRO_CLIENTE
    WHERE C.NUMRUN = :B_NUMRUN_CLI
    ;
    
V_RUT_CLI := TO_CHAR(:B_NUMRUN_CLI,'99G999G999')||'-'||V_DVRUN_CLI;
IF EXTRACT(MONTH FROM V_FECHA_CUMPLE) = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,1)) THEN
    IF V_TOTAL_AHORRADO BETWEEN 0 AND :B_MONTO_AHORRADO1 THEN
        V_MONTO_GIFTCARD := 0;
    ELSIF V_TOTAL_AHORRADO BETWEEN :B_MONTO_AHORRADO2 AND :B_MONTO_AHORRADO3 THEN
        V_MONTO_GIFTCARD := :B_MONTO_GIFTCARD1;
    ELSIF V_TOTAL_AHORRADO BETWEEN :B_MONTO_AHORRADO4 AND :B_MONTO_AHORRADO5 THEN
        V_MONTO_GIFTCARD := :B_MONTO_GIFTCARD2;    
    ELSIF V_TOTAL_AHORRADO BETWEEN :B_MONTO_AHORRADO6 AND :B_MONTO_AHORRADO7 THEN
        V_MONTO_GIFTCARD := :B_MONTO_GIFTCARD3;
    ELSIF V_TOTAL_AHORRADO BETWEEN :B_MONTO_AHORRADO8 AND :B_MONTO_AHORRADO9 THEN
        V_MONTO_GIFTCARD := :B_MONTO_GIFTCARD4;
    END IF;
END IF
    ;
    
INSERT INTO CUMPLEANNO_CLIENTE VALUES (V_NRO_CLI,V_RUT_CLI,INITCAP(V_NOMBRE_CLI),V_PROFESION,V_FECHA_CUMPLEANO,V_MONTO_GIFTCARD,V_OBSVERVACION);
COMMIT;    

END
;






























