--CASO 5

--BIND
VAR B_BONO_PORC_COLACION NUMBER;
EXEC :B_BONO_PORC_COLACION := 20;
DECLARE

V_RUN             EMPLEADO.NUMRUN_EMP%TYPE;
V_DVRUN           EMPLEADO.DVRUN_EMP%TYPE;
V_PNOMBRE         EMPLEADO.PNOMBRE_EMP%TYPE;
V_SNOMBRE         EMPLEADO.SNOMBRE_EMP%TYPE;
V_APPATERNO       EMPLEADO.APPATERNO_EMP%TYPE;
V_APMATERNO       EMPLEADO.APMATERNO_EMP%TYPE;
V_FECHA_CONTRATO  EMPLEADO.FECHA_CONTRATO%TYPE;
V_SUELDO_BASE     EMPLEADO.SUELDO_BASE%TYPE;
V_NOMBRE_COMUNA   COMUNA.NOMBRE_COMUNA%TYPE;
V_PORC_DESCTO_AFP AFP.PORC_DESCTO_AFP%TYPE;
V_PORC_DESCTO_SALUD NUMBER(2);

V_ANNO_TRIBUTARIO NUMBER(4);
V_ID_EMP NUMBER(6) := 100;
V_NOMBRE_COMPLETO VARCHAR2(110);
V_NOMBRE_CARGO VARCHAR2(30);
V_EXISTE_EMP NUMBER(2);
V_MESES_TRABAJADOS NUMBER(2);
V_ANNOS_TRABAJADOS NUMBER(3);
V_SUELDO_BASE_ANUAL NUMBER(15);
V_CANT_ARRIENDO_CAMION NUMBER(3);
V_BONO_ANNOS_ANUAL NUMBER(15);
V_BONO_ESPECIAL_ANUAL NUMBER(15);
V_BONO_MOVILIZACION NUMBER(8);
V_BONO_COLACION_ANUAL NUMBER(8);

V_MONTO_IMPONIBLE NUMBER(15);
V_PORC_BONO_ANNO NUMBER(3);
V_SUELDO_BRUTO_ANUAL NUMBER(10);
V_DESC_LEGALES NUMBER(10);

BEGIN

FOR I IN 1..23 LOOP
        SELECT 
                E.NUMRUN_EMP, E.DVRUN_EMP,
                E.PNOMBRE_EMP, E.SNOMBRE_EMP, E.APPATERNO_EMP, E.APMATERNO_EMP,
                E.FECHA_CONTRATO,
                E.SUELDO_BASE,
                UPPER(C.NOMBRE_COMUNA),
                A.PORC_DESCTO_AFP,
                TS.PORC_DESCTO_SALUD
        INTO V_RUN,V_DVRUN,V_PNOMBRE,V_SNOMBRE,V_APPATERNO,V_APMATERNO,V_FECHA_CONTRATO,V_SUELDO_BASE,V_NOMBRE_COMUNA,V_PORC_DESCTO_AFP,V_PORC_DESCTO_SALUD
        FROM EMPLEADO E
                    JOIN COMUNA C ON E.ID_COMUNA = C.ID_COMUNA
                    JOIN AFP A ON A.COD_AFP = E.COD_AFP
                    JOIN TIPO_SALUD TS ON TS.COD_TIPO_SAL= E.COD_TIPO_SAL
        WHERE E.ID_EMP= V_ID_EMP;
        
        V_ANNO_TRIBUTARIO := EXTRACT(YEAR FROM SYSDATE);
        V_NOMBRE_COMPLETO := V_PNOMBRE||' '||V_SNOMBRE||' '||V_APPATERNO||' '||V_APMATERNO;
        
        --SELECT PARA SABER SI EL EMPLEADO EXISTE EN LA TABLA CAMION Y GUARDARLO EN UNAVARIABLE DE EXISTENCIA
        SELECT COUNT(*) INTO V_EXISTE_EMP FROM CAMION WHERE ID_EMP = V_ID_EMP;
        
        --PREGUNTAR SI V_EXISTE_CAMION ES DISTINTO A CERO SIGNIFICA QUE TIENE CAMIONES A SU CARGO PARA ASI TENER EL CARGO DEL EMPLEADO QUE ME PIDEN
        IF V_EXISTE_EMP > 0 THEN
            V_NOMBRE_CARGO := 'Encargado de Arriendos';
        ELSE
            V_NOMBRE_CARGO := 'Labores Administrativas';
        END IF;
        
        --USANDO "CASE" PARA OBTENER LOS MESES TRABAJADOS (SI TRABAJA MAS DE 1 AÑO IGUAL SE DEBEN PONER 12 MESES, EN CASO CONTRARIO SE DEBEN PONER LOS MESE CORRESPONDIENTES
        V_MESES_TRABAJADOS :=
        CASE
            WHEN TRUNC(MONTHS_BETWEEN(SYSDATE,V_FECHA_CONTRATO)) >= 12 THEN 12
            ELSE 12-EXTRACT(MONTH FROM V_FECHA_CONTRATO)+1
        END;
        
        --AÑOS TRABAJADOS
        V_ANNOS_TRABAJADOS := TRUNC(MONTHS_BETWEEN(SYSDATE,V_FECHA_CONTRATO)/12);
        
        --SUELDO BASE ANUAL
        V_SUELDO_BASE_ANUAL := V_SUELDO_BASE*V_MESES_TRABAJADOS;
        
        /*BONO AÑOS ANUAL*/--USAR TABLA CON NONEQUIJOIN EN LA TABLA TRAMO_ANTIGUEDAD
    
        
        /*BONO ESPECIAL ANUAL POR ARRIENDO DE CAMIONES*/
        --CANTIDAD DE CAMIONES QUE ARRENDO EL AÑO PASADO
        SELECT COUNT(*)
        INTO V_CANT_ARRIENDO_CAMION
        FROM CAMION C JOIN arriendo_camion AC ON C.ID_CAMION = AC.ID_CAMION
        WHERE C.ID_EMP = V_ID_EMP AND EXTRACT(YEAR FROM FECHA_INI_ARRIENDO) = EXTRACT(YEAR FROM SYSDATE)-1;
        --CALCULO DEL BONO
        IF V_NOMBRE_CARGO = 'Encargado de Arriendos' THEN
            V_BONO_ESPECIAL_ANUAL := V_SUELDO_BASE*(V_CANT_ARRIENDO_CAMION*5/100);
        ELSE
            V_BONO_ESPECIAL_ANUAL := V_SUELDO_BASE*(0.12);--12% DE BONO SI NO ARRIENDA CAMIONES
        END IF;
        
        /*MOVILIZACION ANUAL*/
        V_BONO_MOVILIZACION := V_SUELDO_BASE*0.12; --DE BASE TODOS LOS EMPPLEDOS TIENEN 12% DE BONO POR MOVILIZACION
        IF V_NOMBRE_COMUNA = 'MARÍA PINTO' THEN
            V_BONO_MOVILIZACION := V_BONO_MOVILIZACION + (V_SUELDO_BASE*0.20);
        ELSIF V_NOMBRE_COMUNA = 'CURACAVÍ' THEN
            V_BONO_MOVILIZACION := V_BONO_MOVILIZACION + (V_SUELDO_BASE*0.25);
        ELSIF V_NOMBRE_COMUNA = 'TALAGANTE' THEN
            V_BONO_MOVILIZACION := V_BONO_MOVILIZACION + (V_SUELDO_BASE*0.3);
        ELSIF V_NOMBRE_COMUNA = 'EL MONTE' THEN
            V_BONO_MOVILIZACION := V_BONO_MOVILIZACION + (V_SUELDO_BASE*0.35);
        ELSIF V_NOMBRE_COMUNA = 'BUIN' THEN
            V_BONO_MOVILIZACION := V_BONO_MOVILIZACION + (V_SUELDO_BASE*0.40);
        END IF;
        
        /*BONO COLACION ANUAL*/
        V_BONO_COLACION_ANUAL := (V_SUELDO_BASE*:B_BONO_PORC_COLACION/100)*V_MESES_TRABAJADOS;
        
        /*DESCUENTOS LEGALES : UTILIZAR TABLAS AFP Y TIPO_SALUD*/
        
        --PRIMERO SE DEBE OBTENER EL SUELDO IMPONIBLE
        
        --CON LA SENTENCIA IF NOS ASEGURAMOS QUE CUANDO V_ANNOS_TRABAJADOS SEA DISTINTO DE 0 SE EJECUTE EL NONEQUIJOIN
        V_PORC_BONO_ANNO := 0;
        IF V_ANNOS_TRABAJADOS <> 0 THEN
            SELECT PORCENTAJE--PORCENTAJE ANUAL BONO
                INTO V_PORC_BONO_ANNO
                FROM TRAMO_ANTIGUEDAD--NONEQUIJOIN
            WHERE V_ANNOS_TRABAJADOS BETWEEN TRAMO_INF AND TRAMO_SUP AND ANNO_VIG = EXTRACT(YEAR FROM SYSDATE)-1
            ;
        END IF;
        V_BONO_ANNOS_ANUAL:=V_SUELDO_BASE*V_PORC_BONO_ANNO/100;
        V_DESC_LEGALES := (V_SUELDO_BASE*V_PORC_DESCTO_AFP/100)+(V_SUELDO_BASE*V_PORC_DESCTO_SALUD);
        V_SUELDO_BRUTO_ANUAL := V_SUELDO_BASE_ANUAL+(V_SUELDO_BASE*V_PORC_BONO_ANNO/100)+V_BONO_ESPECIAL_ANUAL+V_BONO_MOVILIZACION+V_BONO_COLACION_ANUAL;
        
        V_MONTO_IMPONIBLE:= (V_SUELDO_BASE_ANUAL+(V_SUELDO_BASE*V_PORC_BONO_ANNO/100)+V_BONO_ESPECIAL_ANUAL)-V_DESC_LEGALES;
        
         
        INSERT INTO INFO_SII VALUES(V_ANNO_TRIBUTARIO,V_ID_EMP,V_RUN||'-'||V_DVRUN,V_NOMBRE_COMPLETO,V_NOMBRE_CARGO,V_MESES_TRABAJADOS,V_ANNOS_TRABAJADOS,V_SUELDO_BASE,
        V_SUELDO_BASE_ANUAL,V_BONO_ANNOS_ANUAL,V_BONO_ESPECIAL_ANUAL,V_BONO_MOVILIZACION,V_BONO_COLACION_ANUAL,V_DESC_LEGALES,V_SUELDO_BRUTO_ANUAL,V_MONTO_IMPONIBLE);
        V_ID_EMP := V_ID_EMP+10;
END LOOP;
END
;
/
SELECT PORCENTAJE
INTO V_PORC_BONO_ANNO
FROM TRAMO_ANTIGUEDAD
    WHERE V_ANNOS_TRABAJADOS BETWEEN TRAMO_INF AND TRAMO_SUP AND ANNO_VIG = EXTRACT(YEAR FROM SYSDATE)-1;

SELECT PORCENTAJE
--INTO V_PORC_BONO_ANNO
FROM TRAMO_ANTIGUEDAD
    WHERE 10 BETWEEN TRAMO_INF AND TRAMO_SUP AND ANNO_VIG = EXTRACT(YEAR FROM SYSDATE)-1
/

    SELECT 
            E.NUMRUN_EMP, E.DVRUN_EMP,
            E.PNOMBRE_EMP, E.SNOMBRE_EMP, E.APPATERNO_EMP, E.APMATERNO_EMP,
            E.FECHA_CONTRATO,
            E.SUELDO_BASE,
            UPPER(C.NOMBRE_COMUNA),
            A.PORC_DESCTO_AFP,
            TS.PORC_DESCTO_SALUD
    INTO V_RUN,V_DVRUN,V_PNOMBRE,V_SNOMBRE,V_APPATERNO,V_APMATERNO,V_FECHA_CONTRATO,V_SUELDO_BASE,V_NOMBRE_COMUNA
    FROM EMPLEADO E
                JOIN COMUNA C ON E.ID_COMUNA = C.ID_COMUNA
                JOIN AFP A ON A.COD_AFP = E.COD_AFP
                JOIN TIPO_SALUD TS ON TS.COD_TIPO_SAL= E.COD_TIPO_SAL
    WHERE E.ID_EMP= 100;
