--CASO 4
VAR B_ANNO_PROCESO NUMBER;
EXEC :B_ANNO_PROCESO := 2020;

VAR B_UTILIDAD NUMBER;
EXEC :B_UTILIDAD := 200000000;

VAR B_PORC_UTILIDADES NUMBER;
EXEC :B_PORC_UTILIDADES := 0.3;

VAR B_TRAMO_SUELDO1 NUMBER;
EXEC :B_TRAMO_SUELDO1 := 320000;
VAR B_TRAMO_SUELDO2 NUMBER;
EXEC :B_TRAMO_SUELDO2 := 600000;
VAR B_TRAMO_SUELDO3 NUMBER;
EXEC :B_TRAMO_SUELDO3 := 600001;
VAR B_TRAMO_SUELDO4 NUMBER;
EXEC :B_TRAMO_SUELDO4 := 1300000;
VAR B_TRAMO_SUELDO5 NUMBER;
EXEC :B_TRAMO_SUELDO5 := 1300001;
VAR B_TRAMO_SUELDO6 NUMBER;
EXEC :B_TRAMO_SUELDO6 := 1800000;
VAR B_TRAMO_SUELDO7 NUMBER;
EXEC :B_TRAMO_SUELDO7 := 1800001;
VAR B_TRAMO_SUELDO8 NUMBER;
EXEC :B_TRAMO_SUELDO8 := 2200000;
VAR B_TRAMO_SUELDO9 NUMBER;
EXEC :B_TRAMO_SUELDO9 := 2200001;

VAR B_PORC_BONIF1 NUMBER
EXEC :B_PORC_BONIF1 := 0.35;
VAR B_PORC_BONIF2 NUMBER
EXEC :B_PORC_BONIF2 := 0.25;
VAR B_PORC_BONIF3 NUMBER
EXEC :B_PORC_BONIF3 := 0.20;
VAR B_PORC_BONIF4 NUMBER
EXEC :B_PORC_BONIF4 := 0.15;
VAR B_PORC_BONIF5 NUMBER
EXEC :B_PORC_BONIF5 := 0.05;
DECLARE

V_ID_EMP                EMPLEADO.ID_EMP%TYPE := 100;
V_SUELDO_BASE           EMPLEADO.SUELDO_BASE%TYPE;
V_VALOR_BONIF_UTILIDAD  BONIF_POR_UTILIDAD.VALOR_BONIF_UTILIDAD%TYPE;

V_MONTO_A_REPARTIR NUMBER(10);
V_MONTO_POR_TRAMO35 NUMBER(10);
V_MONTO_POR_TRAMO25 NUMBER(10);
V_MONTO_POR_TRAMO20 NUMBER(10);
V_MONTO_POR_TRAMO15 NUMBER(10);
V_MONTO_POR_TRAMO5 NUMBER(10);
V_CANT_EMP NUMBER(3);

V_BONO NUMBER(10);
V_CANTIDAD_EMP_TRAMO1 NUMBER(5);
V_CANTIDAD_EMP_TRAMO2 NUMBER(5);
V_CANTIDAD_EMP_TRAMO3 NUMBER(5);
V_CANTIDAD_EMP_TRAMO4 NUMBER(5);
V_CANTIDAD_EMP_TRAMO5 NUMBER(5);


BEGIN
    SELECT COUNT(ID_EMP)
    INTO V_CANT_EMP
    FROM EMPLEADO;
    
    FOR i IN 1..23 LOOP
        SELECT ID_EMP, SUELDO_BASE
        INTO V_ID_EMP,V_SUELDO_BASE
        FROM EMPLEADO
        WHERE ID_EMP = V_ID_EMP;
        
        V_MONTO_A_REPARTIR := :B_UTILIDAD*:B_PORC_UTILIDADES;
        
        V_MONTO_POR_TRAMO35 := V_MONTO_A_REPARTIR*:B_PORC_BONIF1;
        V_MONTO_POR_TRAMO25 := V_MONTO_A_REPARTIR*:B_PORC_BONIF2;
        V_MONTO_POR_TRAMO20 := V_MONTO_A_REPARTIR*:B_PORC_BONIF3;
        V_MONTO_POR_TRAMO15 := V_MONTO_A_REPARTIR*:B_PORC_BONIF4;
        V_MONTO_POR_TRAMO5 := V_MONTO_A_REPARTIR*:B_PORC_BONIF5;
        
        V_BONO :=
        CASE
        WHEN V_SUELDO_BASE BETWEEN :B_TRAMO_SUELDO1 AND :B_TRAMO_SUELDO2 THEN V_MONTO_POR_TRAMO35
        WHEN V_SUELDO_BASE BETWEEN :B_TRAMO_SUELDO3 AND :B_TRAMO_SUELDO4 THEN V_MONTO_POR_TRAMO25
        WHEN V_SUELDO_BASE BETWEEN :B_TRAMO_SUELDO5 AND :B_TRAMO_SUELDO6 THEN V_MONTO_POR_TRAMO20
        WHEN V_SUELDO_BASE BETWEEN :B_TRAMO_SUELDO7 AND :B_TRAMO_SUELDO8 THEN V_MONTO_POR_TRAMO15
        WHEN V_SUELDO_BASE >= :B_TRAMO_SUELDO9 THEN V_MONTO_POR_TRAMO5
        END;
        
        SELECT
        COUNT(CASE
        WHEN SUELDO_BASE BETWEEN :B_TRAMO_SUELDO1 AND :B_TRAMO_SUELDO2 THEN ID_EMP
        END)
        INTO V_CANTIDAD_EMP_TRAMO1
        FROM EMPLEADO;
        
        SELECT
        COUNT(CASE
        WHEN SUELDO_BASE BETWEEN :B_TRAMO_SUELDO3 AND :B_TRAMO_SUELDO4 THEN ID_EMP
        END)
        INTO V_CANTIDAD_EMP_TRAMO2
        FROM EMPLEADO;
        
        SELECT
        COUNT(CASE
        WHEN SUELDO_BASE BETWEEN :B_TRAMO_SUELDO5 AND :B_TRAMO_SUELDO6 THEN ID_EMP
        END)
        INTO V_CANTIDAD_EMP_TRAMO3
        FROM EMPLEADO;
        
        SELECT
        COUNT(CASE
        WHEN SUELDO_BASE BETWEEN :B_TRAMO_SUELDO7 AND :B_TRAMO_SUELDO8 THEN ID_EMP
        END)
        INTO V_CANTIDAD_EMP_TRAMO4
        FROM EMPLEADO;
        
        SELECT
        COUNT(CASE
        WHEN SUELDO_BASE >= :B_TRAMO_SUELDO9 THEN ID_EMP
        END)
        INTO V_CANTIDAD_EMP_TRAMO5
        FROM EMPLEADO;
        
        IF V_SUELDO_BASE BETWEEN :B_TRAMO_SUELDO1 AND :B_TRAMO_SUELDO2 THEN
            V_VALOR_BONIF_UTILIDAD := ROUND(V_BONO/V_CANTIDAD_EMP_TRAMO1);
        ELSIF V_SUELDO_BASE BETWEEN :B_TRAMO_SUELDO3 AND :B_TRAMO_SUELDO4 THEN
            V_VALOR_BONIF_UTILIDAD := ROUND(V_BONO/V_CANTIDAD_EMP_TRAMO2);
        ELSIF V_SUELDO_BASE BETWEEN :B_TRAMO_SUELDO5 AND :B_TRAMO_SUELDO6 THEN
            V_VALOR_BONIF_UTILIDAD := ROUND(V_BONO/V_CANTIDAD_EMP_TRAMO3);
        ELSIF V_SUELDO_BASE BETWEEN :B_TRAMO_SUELDO7 AND :B_TRAMO_SUELDO8 THEN
            V_VALOR_BONIF_UTILIDAD := ROUND(V_BONO/V_CANTIDAD_EMP_TRAMO4);
        ELSIF V_SUELDO_BASE >= :B_TRAMO_SUELDO9 THEN
            V_VALOR_BONIF_UTILIDAD := ROUND(V_BONO/V_CANTIDAD_EMP_TRAMO5);
        END IF;
       

        
        INSERT INTO BONIF_POR_UTILIDAD VALUES(:B_ANNO_PROCESO,V_ID_EMP,V_SUELDO_BASE,V_VALOR_BONIF_UTILIDAD);
        V_ID_EMP := V_ID_EMP+10;
    END LOOP;
END;