CREATE SEQUENCE SQ_COD_ERROR;
DECLARE
    
    R_USUARIO_CLAVE USUARIO_CLAVE%ROWTYPE;
    V_FACTOR NUMBER(2);
    V_SQLERRM VARCHAR2(250);
    V_CANT_CUOTAS NUMBER(3);
    
    CURSOR C_SOCIOS IS
    SELECT
        NRO_SOCIO,
        NUMRUN,DVRUN,
        PNOMBRE,SNOMBRE,APPATERNO,APMATERNO,
        FECHA_NACIMIENTO,
        TRUNC(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) AS EDAD,
        P.NOMBRE_PROVINCIA,
        R.NOMBRE_REGION
    FROM SOCIO S
                JOIN COMUNA C ON S.COD_COMUNA = C.COD_COMUNA AND S.COD_PROVINCIA = C.COD_PROVINCIA AND S.COD_REGION = C.COD_REGION
                JOIN PROVINCIA P ON C.COD_PROVINCIA = P.COD_PROVINCIA AND C.COD_REGION = P.COD_REGION
                JOIN REGION R ON P.COD_REGION = R.COD_REGION
    ORDER BY NRO_SOCIO;


BEGIN
    
    FOR R_SOCIOS IN C_SOCIOS LOOP
        
        R_USUARIO_CLAVE.NRO_SOCIO    := R_SOCIOS.NRO_SOCIO;
        R_USUARIO_CLAVE.NUMRUN_SOCIO := R_SOCIOS.NUMRUN||'-'||R_SOCIOS.DVRUN;
        R_USUARIO_CLAVE.NOMBRE_SOCIO := R_SOCIOS.PNOMBRE||' '||R_SOCIOS.SNOMBRE||' '||R_SOCIOS.APPATERNO||' '||R_SOCIOS.APMATERNO;
        
        --NOMBRE_USUARIO*********************************************
        R_USUARIO_CLAVE.NOMBRE_USUARIO := INITCAP(SUBSTR(R_SOCIOS.PNOMBRE,1,3))||LENGTH(R_SOCIOS.APPATERNO)||'*'||SUBSTR(R_SOCIOS.NUMRUN,-3,2);
        
        IF R_SOCIOS.NOMBRE_REGION IN ('Tarapacá','Antofagasta','Atacama ','Coquimbo') THEN
            R_USUARIO_CLAVE.NOMBRE_USUARIO := R_USUARIO_CLAVE.NOMBRE_USUARIO||(SUBSTR(R_SOCIOS.NOMBRE_PROVINCIA,2,2));
        ELSIF R_SOCIOS.NOMBRE_REGION IN ('Valparaíso','Del Libertador Gral. Bernardo O’Higgins','Del Maule','Del Biobío','De la Araucanía') THEN
             R_USUARIO_CLAVE.NOMBRE_USUARIO := R_USUARIO_CLAVE.NOMBRE_USUARIO||(SUBSTR(R_SOCIOS.NOMBRE_PROVINCIA,-2,2));
        ELSIF R_SOCIOS.NOMBRE_REGION IN ('De Los Lagos','Aysén del Gral.Carlos Ibáñez del Campo','De Magallanes y de la Antártica Chilena','Metropolitana de Santiago') THEN
            R_USUARIO_CLAVE.NOMBRE_USUARIO := R_USUARIO_CLAVE.NOMBRE_USUARIO||(SUBSTR(R_SOCIOS.NOMBRE_PROVINCIA,1,1))||(SUBSTR(R_SOCIOS.NOMBRE_PROVINCIA,-1,1));
        ELSIF R_SOCIOS.NOMBRE_REGION IN ('De Los Ríos','Arica y Parinacota','De Ñuble') THEN
            R_USUARIO_CLAVE.NOMBRE_USUARIO := R_USUARIO_CLAVE.NOMBRE_USUARIO||(SUBSTR(R_SOCIOS.NOMBRE_PROVINCIA,1,2));
        END IF;
        
        R_USUARIO_CLAVE.NOMBRE_USUARIO := R_USUARIO_CLAVE.NOMBRE_USUARIO||'.';
        
        
        IF R_SOCIOS.EDAD < 60 THEN
            R_USUARIO_CLAVE.NOMBRE_USUARIO := R_USUARIO_CLAVE.NOMBRE_USUARIO||(EXTRACT(MONTH FROM SYSDATE)*SUBSTR(R_SOCIOS.EDAD,1,1));
            
        ELSIF R_SOCIOS.EDAD >= 60 THEN
            BEGIN
            SELECT FACTOR
            INTO V_FACTOR
            FROM TRAMO_3RA_EDAD
            WHERE R_SOCIOS.EDAD BETWEEN RANGO_EDAD_MIN AND RANGO_EDAD_MAX;
        EXCEPTION WHEN TOO_MANY_ROWS THEN
            V_FACTOR := 0;
            V_SQLERRM := SQLERRM;
            INSERT INTO ERROR_PROCESO VALUES(SQ_COD_ERROR.NEXTVAL,'Error  al obtener el factor para los 64 años del socio N° '||R_SOCIOS.NRO_SOCIO,V_SQLERRM);
        END;
        R_USUARIO_CLAVE.NOMBRE_USUARIO := R_USUARIO_CLAVE.NOMBRE_USUARIO||(EXTRACT(MONTH FROM SYSDATE)*V_FACTOR);
        END IF;
        
        --USUARIO_CLAVE
        R_USUARIO_CLAVE.CLAVE_USUARIO := UPPER(SUBSTR(R_SOCIOS.APPATERNO,-3,3))||(EXTRACT(YEAR FROM R_SOCIOS.FECHA_NACIMIENTO)*2)||(R_SOCIOS.NRO_SOCIO*3)||TO_CHAR(SYSDATE,'MMYYYY')||'*';
        
        BEGIN
            SELECT COUNT(CCS.NRO_CUOTA)
            INTO V_CANT_CUOTAS
            FROM SOCIO S
                    JOIN CREDITO_SOCIO CS ON S.NRO_SOCIO = CS.NRO_SOCIO
                    JOIN CUOTA_CREDITO_SOCIO CCS ON CS.NRO_SOLIC_CREDITO = CCS.NRO_SOLIC_CREDITO
            WHERE S.NRO_SOCIO = R_SOCIOS.NRO_SOCIO
            GROUP BY S.NRO_SOCIO
            ;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            V_CANT_CUOTAS := 0;
            V_SQLERRM := SQLERRM;
            INSERT INTO ERROR_PROCESO VALUES(SQ_COD_ERROR.NEXTVAL,'Error  al obtener total cuotas ultimo credito para el socio N° '||R_SOCIOS.NRO_SOCIO,V_SQLERRM);
        END;
        
        R_USUARIO_CLAVE.CLAVE_USUARIO := R_USUARIO_CLAVE.CLAVE_USUARIO||(TRUNC(V_CANT_CUOTAS/2));
        
        INSERT INTO USUARIO_CLAVE VALUES R_USUARIO_CLAVE;
    END LOOP;

END;
/
SELECT * FROM USUARIO_CLAVE
ORDER BY 1;
SELECT * FROM ERROR_PROCESO
ORDER BY 1;
