--CASO 1

--BIND
VAR B_ANNO_PROCESO NUMBER;
EXEC :B_ANNO_PROCESO := 2021;

VAR B_COMUNA1 VARCHAR2;
EXEC :B_COMUNA1 := 'María Pinto';
VAR B_COMUNA2 VARCHAR2;
EXEC :B_COMUNA2 := 'Curacaví'
VAR B_COMUNA3 VARCHAR2;
EXEC :B_COMUNA3 := 'Talagante'
VAR B_COMUNA4 VARCHAR2;
EXEC :B_COMUNA4 := 'El Monte'
VAR B_COMUNA5 VARCHAR2;
EXEC :B_COMUNA5 := 'Buin'

VAR B_VALOR_MOV1 NUMBER;
EXEC :B_VALOR_MOV1 := 20000;
VAR B_VALOR_MOV2 NUMBER;
EXEC :B_VALOR_MOV2 := 25000;
VAR B_VALOR_MOV3 NUMBER;
EXEC :B_VALOR_MOV3 := 30000;
VAR B_VALOR_MOV4 NUMBER;
EXEC :B_VALOR_MOV4 := 35000;
VAR B_VALOR_MOV5 NUMBER;
EXEC :B_VALOR_MOV5 := 40000;

DECLARE
V_ID_EMP            PROY_MOVILIZACION.ID_EMP%TYPE := 100;
V_NUMRUN_EMP        PROY_MOVILIZACION.NUMRUN_EMP%TYPE;
V_DVRUN_EMP         PROY_MOVILIZACION.DVRUN_EMP%TYPE;
V_NOMBRE_EMP        PROY_MOVILIZACION.NOMBRE_EMPLEADO%TYPE;
V_NOMBRE_COMUNA     PROY_MOVILIZACION.NOMBRE_COMUNA%TYPE;
V_SUELDO_BASE       PROY_MOVILIZACION.SUELDO_BASE%TYPE;
V_PORC_MOVIL        PROY_MOVILIZACION.PORC_MOVIL_NORMAL%TYPE;
V_VALOR_MOV_NORMAL  PROY_MOVILIZACION.VALOR_MOVIL_NORMAL%TYPE;
V_VALOR_MOV_EXTRA   PROY_MOVILIZACION.VALOR_MOVIL_EXTRA%TYPE;
V_VALOR_TOTAL_MOVIL PROY_MOVILIZACION.VALOR_TOTAL_MOVIL%TYPE;


BEGIN
FOR i IN 1..23 LOOP
    SELECT
            
            E.NUMRUN_EMP,
            E.DVRUN_EMP,
            E.PNOMBRE_EMP||' '||E.SNOMBRE_EMP||' '||E.APPATERNO_EMP||' '||E.APMATERNO_EMP,
            C.NOMBRE_COMUNA,
            E.SUELDO_BASE
    INTO V_NUMRUN_EMP,V_DVRUN_EMP,V_NOMBRE_EMP,V_NOMBRE_COMUNA,V_SUELDO_BASE
    FROM EMPLEADO E
                    JOIN COMUNA C ON E.ID_COMUNA = C.ID_COMUNA
    WHERE ID_EMP = V_ID_EMP
    ;
    
    V_PORC_MOVIL := TRUNC(V_SUELDO_BASE/100000);
    V_VALOR_MOV_NORMAL := ROUND(V_SUELDO_BASE*V_PORC_MOVIL/100);
    
    IF V_NOMBRE_COMUNA = :B_COMUNA1 THEN
        V_VALOR_MOV_EXTRA := :B_VALOR_MOV1;
    ELSIF V_NOMBRE_COMUNA = :B_COMUNA2 THEN
        V_VALOR_MOV_EXTRA := :B_VALOR_MOV2;
    ELSIF V_NOMBRE_COMUNA = :B_COMUNA3 THEN
        V_VALOR_MOV_EXTRA := :B_VALOR_MOV3;
    ELSIF V_NOMBRE_COMUNA = :B_COMUNA4 THEN
        V_VALOR_MOV_EXTRA := :B_VALOR_MOV4;
    ELSIF V_NOMBRE_COMUNA = :B_COMUNA5 THEN
        V_VALOR_MOV_EXTRA := :B_VALOR_MOV5;
    ELSE
        V_VALOR_MOV_EXTRA := 0;
    END IF;
    
    
    V_VALOR_TOTAL_MOVIL := V_VALOR_MOV_NORMAL + V_VALOR_MOV_EXTRA;
    
    INSERT INTO PROY_MOVILIZACION VALUES (:B_ANNO_PROCESO,V_ID_EMP,V_NUMRUN_EMP,V_DVRUN_EMP,INITCAP(V_NOMBRE_EMP),V_NOMBRE_COMUNA,
                                          V_SUELDO_BASE,V_PORC_MOVIL,V_VALOR_MOV_NORMAL,V_VALOR_MOV_EXTRA,V_VALOR_TOTAL_MOVIL);
    COMMIT;
    V_ID_EMP := V_ID_EMP+10;
END LOOP;
END
;


/
SELECT * FROM EMPLEADO;