CREATE OR REPLACE PROCEDURE SP_GUARDAR_DEPTOS_MOROSO
            (P_ANNO_MES_PCGC NUMBER, P_ID_EDIF NUMBER, P_NOMBRE_EDIF VARCHAR2,
            P_RUN_ADMINISTRADOR VARCHAR2, P_NOMBRE_ADMNISTRADOR VARCHAR2,
            P_NRO_DEPTO NUMBER, P_RUN_RESPONSABLE_PAGO_GC VARCHAR2,
            P_NOMBRE_RESPONSABLE_PAGO_GC VARCHAR2, P_VALOR_MULTA_PAGO_CERO NUMBER,
            P_OBSERVACION VARCHAR2)
/*PROCEDIMIENTO QUE INSERTA DATOS EN LA TABLA GASTO_COMUN_PAGO_CERO DE LOS DEPTOS QUE NO HAN
PAGADO GASTOS COMUNES*/
IS
BEGIN
    INSERT INTO GASTO_COMUN_PAGO_CERO VALUES(P_ANNO_MES_PCGC,P_ID_EDIF,P_NOMBRE_EDIF,
                                            P_RUN_ADMINISTRADOR,P_NOMBRE_ADMNISTRADOR,
                                            P_NRO_DEPTO,P_RUN_RESPONSABLE_PAGO_GC,
                                            P_NOMBRE_RESPONSABLE_PAGO_GC,P_VALOR_MULTA_PAGO_CERO,
                                            P_OBSERVACION);
    COMMIT;
END SP_GUARDAR_DEPTOS_MOROSO;
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_GENERA_INFO_DEPTO_NO_PAGO(P_ANNO_MES_PROCESO NUMBER, P_UF NUMBER)
/*PROCEDIMIENTO PRINCIPAL QUE NOS PERMITE GENERAR LOS DEPTOS QUE NO HAN PAGADO
HASTA 2 PERIODOS DE GASTOS COMUNES.
CONSIDERAR UF=29509 Y ANNO_MES_PROCESO = 202105*/
IS
    CURSOR C_DEPTO_MOROSOS IS
    SELECT
          E.ID_EDIF, 
          E.NOMBRE_EDIF,
          TO_CHAR(A.NUMRUN_ADM,'09G999G999')||'-'||A.DVRUN_ADM AS RUN_ADMIN,
          A.PNOMBRE_ADM||' '||A.SNOMBRE_ADM||' '||A.APPATERNO_ADM||' '||A.APMATERNO_ADM AS NOMBRE_ADMIN,
          D.NRO_DEPTO,
          TO_CHAR(RPGC.NUMRUN_RPGC,'09G999G999')||'-'||RPGC.DVRUN_RPGC AS RUN_RPGC,
          RPGC.PNOMBRE_RPGC||' '||RPGC.SNOMBRE_RPGC||' '||RPGC.APPATERNO_RPGC||' '||RPGC.APMATERNO_RPGC AS NOMBRE_RPGC,
          GC.FECHA_PAGO_GC
    FROM EDIFICIO E
                    JOIN ADMINISTRADOR A ON E.NUMRUN_ADM = A.NUMRUN_ADM
                    JOIN DEPARTAMENTO D ON E.ID_EDIF = D.ID_EDIF
                    JOIN GASTO_COMUN GC ON D.ID_EDIF=GC.ID_EDIF AND D.NRO_DEPTO=GC.NRO_DEPTO
                    JOIN RESPONSABLE_PAGO_GASTO_COMUN RPGC ON GC.NUMRUN_RPGC=RPGC.NUMRUN_RPGC
    WHERE GC.ANNO_MES_PCGC = P_ANNO_MES_PROCESO
    ORDER BY 2,5;
    
    V_NO_PAGO_1_MES NUMBER(2);
    V_NO_PAGO_2_MES NUMBER(2);
    V_MULTA NUMBER(6);
    V_OBSERVACION VARCHAR(80);
BEGIN
    
    FOR R_DEPTO_MOROSOS IN C_DEPTO_MOROSOS LOOP
        
        --SI V_NO_PAGO_1_MES ES = 0 -> DEUDOR DEL MES ANTERIOR(ABRIL)
        SELECT COUNT(*)
        INTO V_NO_PAGO_1_MES
        FROM PAGO_GASTO_COMUN
        WHERE ANNO_MES_PCGC = P_ANNO_MES_PROCESO-1
              AND ID_EDIF = R_DEPTO_MOROSOS.ID_EDIF
              AND NRO_DEPTO = R_DEPTO_MOROSOS.NRO_DEPTO;
              
        
        IF V_NO_PAGO_1_MES = 0 THEN
            --SI V_NO_PAGO_2_MES ES = 0 -> DEUDOR DEL MES ANTERIOR(MARZO)    
            SELECT COUNT(*)
            INTO V_NO_PAGO_2_MES
            FROM PAGO_GASTO_COMUN
            WHERE ANNO_MES_PCGC = P_ANNO_MES_PROCESO-2
                  AND ID_EDIF = R_DEPTO_MOROSOS.ID_EDIF
                  AND NRO_DEPTO = R_DEPTO_MOROSOS.NRO_DEPTO;
            
            IF V_NO_PAGO_2_MES = 0 THEN
                V_MULTA := P_UF*4;
                V_OBSERVACION := 'Se realizará el corte de combustible y agua a contar del '||R_DEPTO_MOROSOS.FECHA_PAGO_GC;
            ELSE
                V_MULTA := P_UF*2;
                V_OBSERVACION := 'Se realizará el corte de combustible y agua';
            END IF;
            
            SP_GUARDAR_DEPTOS_MOROSO
            (P_ANNO_MES_PROCESO, R_DEPTO_MOROSOS.ID_EDIF, R_DEPTO_MOROSOS.NOMBRE_EDIF,
            R_DEPTO_MOROSOS.RUN_ADMIN, R_DEPTO_MOROSOS.NOMBRE_ADMIN,
            R_DEPTO_MOROSOS.NRO_DEPTO, R_DEPTO_MOROSOS.RUN_RPGC,
            R_DEPTO_MOROSOS.NOMBRE_RPGC, V_MULTA,
            V_OBSERVACION);
            
            /*ACTUALIZACION DEL CAMPO MULTA_GC DE LA TABLA GASTO_COMUN PARA LOS DEPTOS DEUDORES
            DE GASTOS COMUNES*/
            UPDATE GASTO_COMUN
                SET MULTA_GC = V_MULTA
                WHERE ANNO_MES_PCGC = P_ANNO_MES_PROCESO
                      AND ID_EDIF = R_DEPTO_MOROSOS.ID_EDIF
                      AND NRO_DEPTO = R_DEPTO_MOROSOS.NRO_DEPTO;
            
        END IF;
        
    END LOOP;
    
END SP_GENERA_INFO_DEPTO_NO_PAGO;


/
EXEC SP_GENERA_INFO_DEPTO_NO_PAGO(202105,29509);



/
SELECT * FROM GASTO_COMUN_PAGO_CERO;
DESCRIBE GASTO_COMUN_PAGO_CERO;
SELECT * FROM GASTO_COMUN
WHERE ANNO_MES_PCGC = 202105;