--CASO 1
DESCRIBE CLIENTE;
--BIND
VAR B_RUN_CLI NUMBER;
EXEC :B_RUN_CLI := 22558061;

VAR B_MONTO_TRAMO1 NUMBER;
EXEC :B_MONTO_TRAMO1 := 1000000;

VAR B_MONTO_TRAMO2 NUMBER;
EXEC :B_MONTO_TRAMO2 := 3000000;

VAR B_PESOS_NORMAL NUMBER;
EXEC :B_PESOS_NORMAL := 1200;

VAR B_PESOS_EXTRA1 NUMBER;
EXEC :B_PESOS_EXTRA1 := 100;

VAR B_PESOS_EXTRA2 NUMBER;
EXEC :B_PESOS_EXTRA2 := 300;

VAR B_PESOS_EXTRA3 NUMBER;
EXEC :B_PESOS_EXTRA3 := 550;


DECLARE
V_RUN_CLIENTE CLIENTE_TODOSUMA.RUN_CLIENTE%TYPE;
V_NRO_CLIENTE CLIENTE_TODOSUMA.NRO_CLIENTE%TYPE;
V_DVRUN_CLIENTE CLIENTE.DVRUN%TYPE;
V_NOMBRE_CLI CLIENTE_TODOSUMA.NOMBRE_CLIENTE%TYPE;
V_TIPO_CLIENTE CLIENTE_TODOSUMA.TIPO_CLIENTE%TYPE;
V_MONTO_CREDITOS CLIENTE_TODOSUMA.MONTO_SOLIC_CREDITOS%TYPE;
V_MONTO_PESOS_TODOSUMA CLIENTE_TODOSUMA.MONTO_PESOS_TODOSUMA%TYPE;

BEGIN
    SELECT
            C.NRO_CLIENTE,
            C.DVRUN,
            C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO,
            TC.NOMBRE_TIPO_CLIENTE,
            SUM(MONTO_SOLICITADO)
    INTO V_NRO_CLIENTE,V_DVRUN_CLIENTE,V_NOMBRE_CLI,V_TIPO_CLIENTE,V_MONTO_CREDITOS       
    FROM CLIENTE C
                JOIN TIPO_CLIENTE TC ON C.COD_TIPO_CLIENTE = TC.COD_TIPO_CLIENTE
                JOIN CREDITO_CLIENTE CC ON C.NRO_CLIENTE = CC.NRO_CLIENTE
    WHERE C.NUMRUN = :B_RUN_CLI AND EXTRACT(YEAR FROM FECHA_SOLIC_CRED) = EXTRACT(YEAR FROM SYSDATE)-1
    GROUP BY C.NRO_CLIENTE, C.DVRUN, C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO, TC.NOMBRE_TIPO_CLIENTE;
    
V_RUN_CLIENTE := TO_CHAR(:B_RUN_CLI,'99G999G999')||'-'||V_DVRUN_CLIENTE;

IF V_TIPO_CLIENTE ='Trabajadores independientes' THEN
    IF V_MONTO_CREDITOS < :B_MONTO_TRAMO1 THEN
        V_MONTO_PESOS_TODOSUMA := TRUNC(V_MONTO_CREDITOS/100000)*(:B_PESOS_EXTRA1+:B_PESOS_NORMAL);
    
    ELSIF V_MONTO_CREDITOS BETWEEN :B_MONTO_TRAMO1 AND :B_MONTO_TRAMO2 THEN
        V_MONTO_PESOS_TODOSUMA := TRUNC(V_MONTO_CREDITOS/100000)*(:B_PESOS_EXTRA2+:B_PESOS_NORMAL);
    ELSE
        V_MONTO_PESOS_TODOSUMA := TRUNC(V_MONTO_CREDITOS/100000)*(:B_PESOS_EXTRA3+:B_PESOS_NORMAL);
    END IF;
ELSE
    V_MONTO_PESOS_TODOSUMA := TRUNC(V_MONTO_CREDITOS/100000)*:B_PESOS_NORMAL;
END IF
;

INSERT INTO CLIENTE_TODOSUMA VALUES(V_NRO_CLIENTE,V_RUN_CLIENTE,V_NOMBRE_CLI,V_TIPO_CLIENTE,V_MONTO_CREDITOS,V_MONTO_PESOS_TODOSUMA);
COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR!!');

END
;