
DECLARE
    
    V_NOMBRE_CREDITO CREDITO.NOMBRE_CREDITO%TYPE;
    
    V_NRO_CUOTAS_PEDIDAS NUMBER(3);
    V_NRO_ULTIMA_CUOTA   CUOTA_CREDITO_CLIENTE.NRO_CUOTA%TYPE;
    V_FECHA_ULTIMA_CUOTA CUOTA_CREDITO_CLIENTE.FECHA_VENC_CUOTA%TYPE;
    V_VALOR_ULTIMA_CUOTA CUOTA_CREDITO_CLIENTE.VALOR_CUOTA%TYPE;
    
    
    R_CREDITO_CLIENTE CUOTA_CREDITO_CLIENTE%ROWTYPE;

    TYPE TIPO_INTERESES IS RECORD
    (INTERES1 NUMBER(2,1) := 0.5,
    INTERES2 NUMBER(1) := 1,
    INTERES3 NUMBER(1) := 2
    );
    R_INTERESES TIPO_INTERESES;
    
    TYPE TIPO_CREDITO IS RECORD
    (CREDITO1 VARCHAR2(50) := 'Crédito Hipotecario',
     CREDITO2 VARCHAR2(50) := 'Crédito de Consumo',
     CREDITO3 VARCHAR2(50) := 'Crédito Automotriz'
     );
    R_TIPO_CREDITO  TIPO_CREDITO;

    CURSOR C_CLIENTES_POSTERGAN IS
    SELECT NRO_CLIENTE AS NRO_CLIENTE,
    NRO_SOLIC_CREDITO AS NRO_SOLIC_CREDITO,
    NRO_CUOTAS_POSTERGA AS NRO_CUOTAS_POSTERGA
    FROM CLIENTE_POSTERGA_CUOTA;
    
    R_CLIENTES C_CLIENTES_POSTERGAN%ROWTYPE;
    
BEGIN
    
    OPEN C_CLIENTES_POSTERGAN;
    LOOP
        FETCH C_CLIENTES_POSTERGAN INTO R_CLIENTES;
        EXIT WHEN C_CLIENTES_POSTERGAN%NOTFOUND;
    
        --1. OBTENER EL TIPO DE CREDITO QUE PIDIO EL CLIENTE
        SELECT
                NOMBRE_CREDITO
        INTO V_NOMBRE_CREDITO
        FROM CLIENTE C
                        JOIN CREDITO_CLIENTE CC ON C.NRO_CLIENTE = CC.NRO_CLIENTE
                        JOIN CREDITO CRE ON CC.COD_CREDITO = CRE.COD_CREDITO
        WHERE C.NRO_CLIENTE = R_CLIENTES.NRO_CLIENTE AND CC.NRO_SOLIC_CREDITO = R_CLIENTES.NRO_SOLIC_CREDITO
        ;
        
        
        --CANTIDAD DE CUOTAS QUE PIDIO EL CLIENTE EL AÑO PASADO
        SELECT
                COUNT(*)
        INTO V_NRO_CUOTAS_PEDIDAS
        FROM CREDITO_CLIENTE
        WHERE NRO_CLIENTE = R_CLIENTES.NRO_CLIENTE AND EXTRACT(YEAR FROM FECHA_SOLIC_CRED)= EXTRACT(YEAR FROM SYSDATE)-1;
        
        --NUMERO DE ULTIMA CUOTA, FECHA DE ESA ULTIMA CUOTA, Y SU VALOR
        SELECT
        MAX(NRO_CUOTA),MAX(FECHA_VENC_CUOTA),VALOR_CUOTA
        INTO V_NRO_ULTIMA_CUOTA,V_FECHA_ULTIMA_CUOTA,V_VALOR_ULTIMA_CUOTA
        FROM CUOTA_CREDITO_CLIENTE
        WHERE NRO_SOLIC_CREDITO = R_CLIENTES.NRO_SOLIC_CREDITO
        GROUP BY VALOR_CUOTA;
        
        R_CREDITO_CLIENTE.FECHA_PAGO_CUOTA := NULL;
        R_CREDITO_CLIENTE.MONTO_PAGADO := NULL;
        R_CREDITO_CLIENTE.SALDO_POR_PAGAR := NULL;
        R_CREDITO_CLIENTE.COD_FORMA_PAGO := NULL;
        
        IF V_NOMBRE_CREDITO = R_TIPO_CREDITO.CREDITO1 THEN
            
            IF R_CLIENTES.NRO_CUOTAS_POSTERGA = 1 THEN
                R_CREDITO_CLIENTE.NRO_SOLIC_CREDITO := R_CLIENTES.NRO_SOLIC_CREDITO;
                R_CREDITO_CLIENTE.NRO_CUOTA := V_NRO_ULTIMA_CUOTA+1;
                R_CREDITO_CLIENTE.FECHA_VENC_CUOTA := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
                R_CREDITO_CLIENTE.VALOR_CUOTA := V_VALOR_ULTIMA_CUOTA;
                INSERT INTO CUOTA_CREDITO_CLIENTE VALUES R_CREDITO_CLIENTE;
                
            ELSIF R_CLIENTES.NRO_CUOTAS_POSTERGA = 2 THEN
                R_CREDITO_CLIENTE.NRO_SOLIC_CREDITO := R_CLIENTES.NRO_SOLIC_CREDITO;
                R_CREDITO_CLIENTE.NRO_CUOTA := V_NRO_ULTIMA_CUOTA+1;
                R_CREDITO_CLIENTE.FECHA_VENC_CUOTA := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
                R_CREDITO_CLIENTE.VALOR_CUOTA := V_VALOR_ULTIMA_CUOTA * (1+(R_INTERESES.INTERES1/100));
                INSERT INTO CUOTA_CREDITO_CLIENTE VALUES R_CREDITO_CLIENTE;
                
                R_CREDITO_CLIENTE.NRO_CUOTA := V_NRO_ULTIMA_CUOTA+1;
                R_CREDITO_CLIENTE.FECHA_VENC_CUOTA := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
                INSERT INTO CUOTA_CREDITO_CLIENTE VALUES R_CREDITO_CLIENTE;

            END IF;
        
        ELSIF V_NOMBRE_CREDITO = R_TIPO_CREDITO.CREDITO2 THEN
        
            IF R_CLIENTES.NRO_CUOTAS_POSTERGA = 1 THEN
                R_CREDITO_CLIENTE.NRO_SOLIC_CREDITO := R_CLIENTES.NRO_SOLIC_CREDITO;
                R_CREDITO_CLIENTE.NRO_CUOTA := V_NRO_ULTIMA_CUOTA+1;
                R_CREDITO_CLIENTE.FECHA_VENC_CUOTA := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
                R_CREDITO_CLIENTE.VALOR_CUOTA := V_VALOR_ULTIMA_CUOTA * (1+(R_INTERESES.INTERES2/100));
                INSERT INTO CUOTA_CREDITO_CLIENTE VALUES R_CREDITO_CLIENTE;
            END IF;
        
        ELSIF V_NOMBRE_CREDITO = R_TIPO_CREDITO.CREDITO3 THEN
        
            IF R_CLIENTES.NRO_CUOTAS_POSTERGA = 1 THEN
                R_CREDITO_CLIENTE.NRO_SOLIC_CREDITO := R_CLIENTES.NRO_SOLIC_CREDITO;
                R_CREDITO_CLIENTE.NRO_CUOTA := V_NRO_ULTIMA_CUOTA+1;
                R_CREDITO_CLIENTE.FECHA_VENC_CUOTA := ADD_MONTHS(V_FECHA_ULTIMA_CUOTA,1);
                R_CREDITO_CLIENTE.VALOR_CUOTA := V_VALOR_ULTIMA_CUOTA * (1+(R_INTERESES.INTERES3/100));
                INSERT INTO CUOTA_CREDITO_CLIENTE VALUES R_CREDITO_CLIENTE;
            END IF;
        
        END IF;
    END LOOP;
    CLOSE C_CLIENTES_POSTERGAN;


END;
/

SELECT * FROM  CLIENTE_POSTERGA_CUOTA;