--CONEXION ORACLE CLOUD BUCKET

/*CONECTADO COMO ADMIN*/
-- 1. CREAR CREDENCIAL -> PERMITIR CREAR UN USUARIO Y CONECTARNOS A LA CUENTA CLOUD
SET DEFINE OFF
BEGIN
    DBMS_CLOUD.CREATE_CREDENTIAL(
        CREDENTIAL_NAME => 'CRED_WILL',
        USERNAME => 'oracleidentitycloudservice/wi.caballero@alumnos.duoc.cl',
        PASSWORD => 'Rf-8]vN#j5G)FZ(p]5Qh'
    );
END;
/

--2. CREAR DIRECTORIO (OBJETO CREADO SOLO POR EL USUARIO ADMIN)
CREATE DIRECTORY DIR_EJEMPLO AS 'DIR_EJEMPLO';
/

--3. VINCULAR EL ARCHIVO DEL BUCKET CON EL DIRECTORIO
BEGIN
    DBMS_CLOUD.GET_OBJECT(
        CREDENTIAL_NAME => 'CRED_WILL',
        OBJECT_URI => 'https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/N1mrVlc_alij8O5JeNzvS4Vwc3-0HfWB5TL6wO5_TdOOLT0t2gqLZCkCEWUde25Z/n/graibobxakcq/b/bucket-ejemplo1-blob/o/foto-ejemplo1.PNG',
        DIRECTORY_NAME => 'DIR_EJEMPLO'
    );
END;
/

--4. HACER "SELECT" PARA VER TODOS LOS ARCHIVOS QUE TENGO EN EL DIRECTORIO
SELECT *
FROM DBMS_CLOUD.LIST_FILES('DIR_EJEMPLO')
ORDER BY OBJECT_NAME;
/

--5. AUTORIZAR AL DIRECTORIO PARA QUE TENGA PERMISOS SOBRE EL USUARIO QUE VAMOS A TRABAJAR
GRANT READ, WRITE ON DIRECTORY DIR_EJEMPLO TO HR;





