--EJEMPLO PRUEBA 2

/***CASO 1***/

/*EJECUTAR COMO ADMIN*/
--CREAR DIRECTORIO
CREATE DIRECTORY FOTOS AS 'FOTOS';
/
--VINCULAR EL BUCKET CON LAS FOTOS AL DIRECTORIO
BEGIN
DBMS_CLOUD.GET_OBJECT(
CREDENTIAL_NAME => 'CRED_WILL',
OBJECT_URI =>'https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/TmR-pIHgM4eLMpFdOEVABaP6Qe2yMSyv30ifMXz73tdymoAdAwfJgyjlR5Dcu7Ik/n/graibobxakcq/b/bucket-ejemplo-pueba2/o/9985891201.PNG',
DIRECTORY_NAME => 'FOTOS'
);
END;
/
--AUTORIZAR AL DIRECTORIO PARA QUE TENGA PERMISOS SOBRE EL USUARIO QUE VAMOS A TRABAJAR
GRANT READ, WRITE ON DIRECTORY FOTOS TO EJEMPLOE2;
/
SELECT *
FROM DBMS_CLOUD.LIST_FILES('FOTOS')
ORDER BY OBJECT_NAME;
/
/*EJECUTAR COMO USUARIO EJEMPLOE2*/
CREATE SEQUENCE SQ_IDERROR;

DECLARE
    
    CURSOR C_FOTO_CIUDADANO IS
    SELECT IDCIUDADANO, FOTO
    FROM CIUDADANO
    ORDER BY IDCIUDADANO;
    
    V_BFILE BFILE;
    
BEGIN
    FOR R_FOTO_CIUDADANO IN C_FOTO_CIUDADANO LOOP
        
        BEGIN
            --BFILENAME -> VA EL NOMBRE DEL DIRECTORIO Y EL NOMBRE DE LA FOTO
            V_BFILE := BFILENAME('FOTOS',R_FOTO_CIUDADANO.IDCIUDADANO||'.PNG');

            UPDATE CIUDADANO
            SET FOTO = R_FOTO_CIUDADANO.FOTO
            WHERE IDCIUDADANO = R_FOTO_CIUDADANO.IDCIUDADANO;
            
            --CARGAR LA FOTO AL BFILE
            DBMS_LOB.OPEN(V_BFILE, DBMS_LOB.FILE_READONLY);        
            DBMS_LOB.LOADFROMFILE(R_FOTO_CIUDADANO.FOTO,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));
            DBMS_LOB.CLOSE(V_BFILE);
            
        EXCEPTION
            WHEN OTHERS THEN
            INSERT INTO REGISTRO_ERROR VALUES(SQ_IDERROR.NEXTVAL,'ERROR AL ACTUALIZAR FOTO POSTULANTE: '||R_FOTO_CIUDADANO.IDCIUDADANO,NULL,NULL);
        END;
             
    END LOOP;
END;
/
SELECT * FROM CIUDADANO;
DESCRIBE CIUDADANO;
SELECT * FROM REGISTRO_ERROR;
DESCRIBE REGISTRO_ERROR;







