--CASO 1

DECLARE

V_NUMBOLETO      CONFIRMACION_BOLETO.NUMBOLETO%TYPE;
V_IDVUELO        CONFIRMACION_BOLETO.IDVUELO%TYPE;
V_CATEGORIA      CONFIRMACION_BOLETO.CATEGORIA%TYPE;
V_PRECIOCOMPRA   CONFIRMACION_BOLETO.PRECIOCOMPRA%TYPE;
V_DESCUENTO_CAT  CONFIRMACION_BOLETO.DESCUENTO_CAT%TYPE;
V_PRECIO_FINAL   CONFIRMACION_BOLETO.PRECIO_FINAL%TYPE;

V_MIN_VUELO      NUMBER(1);
V_MAX_VUELO      NUMBER(2);
V_MIN_BOLETO     NUMBER(1);
V_MAX_BOLETO     NUMBER(2);
V_NRO_CATEGORIA  NUMBER(2);
BEGIN
        
        SELECT MIN(IDVUELO),MAX(IDVUELO)
        INTO V_MIN_VUELO,V_MAX_VUELO
        FROM
        VUELO
        ;
        --PRIMER LOOP-> RECORRERA 12 VUELTAS DE ACUERDO AL NUMERO DE VUELOS (1 VUELO PUEDE TENER MUCHOS BOLETOS)
        FOR i IN V_MIN_VUELO..V_MAX_VUELO LOOP
            
            --SELECCIONAR Y GUARDAR EN VARIABLES EL NRO MIN Y MAX DE BOLETO-> LA SENTENCIA WHERE DETERMINARA QUE VALORES TENGA EL MIN Y MAX Y ESO
            -- A SU VEZ TAMBIEN DETERMINARA EL NUMERO DE VUELTAS DEL SEGUNDO LOOP
            SELECT MIN(NUMBOLETO),MAX(NUMBOLETO)
            INTO V_MIN_BOLETO,V_MAX_BOLETO
            FROM
            BOLETO
            WHERE IDVUELO = i
            ;
            
            FOR j IN V_MIN_BOLETO..V_MAX_BOLETO LOOP
            
                SELECT CATEGORIA,PRECIO
                INTO V_NRO_CATEGORIA,V_PRECIOCOMPRA
                FROM BOLETO
                WHERE IDVUELO = i AND NUMBOLETO = j;
                
                IF V_NRO_CATEGORIA = 1 THEN
                    V_CATEGORIA := 'NORMAL';
                    V_DESCUENTO_CAT := V_PRECIOCOMPRA*0.05;
                    V_PRECIO_FINAL := V_PRECIOCOMPRA-V_DESCUENTO_CAT;
                ELSIF V_NRO_CATEGORIA = 2 THEN
                    V_CATEGORIA := 'EXECUTIVE';
                    V_DESCUENTO_CAT := V_PRECIOCOMPRA*0.1;
                    V_PRECIO_FINAL := V_PRECIOCOMPRA-V_DESCUENTO_CAT;
                ELSIF V_NRO_CATEGORIA = 3 THEN
                    V_CATEGORIA := 'PREMIUM';
                    V_DESCUENTO_CAT := V_PRECIOCOMPRA*0.15;
                    V_PRECIO_FINAL := V_PRECIOCOMPRA-V_DESCUENTO_CAT;
                END IF;
                
            V_IDVUELO:=i;
            V_NUMBOLETO:=j;
            INSERT INTO CONFIRMACION_BOLETO VALUES (V_NUMBOLETO, V_IDVUELO, V_CATEGORIA, V_PRECIOCOMPRA, V_DESCUENTO_CAT, V_PRECIO_FINAL);
            END LOOP;        
        END LOOP;
END
;

/
SELECT * FROM BOLETO WHERE IDVUELO = 12;

SELECT * FROM VUELO;