/*COMO USUARIO ADMIN ORACLE CLOUD*/ 
CREATE DIRECTORY DIR_EJEMPLO_ET1 AS 'DIR_EJEMPLO_ET1';
/
BEGIN
    DBMS_CLOUD.GET_OBJECT(
        CREDENTIAL_NAME => 'CRED_WILL',
        OBJECT_URI => 'LINK_FOTOS_BUCKET',
        DIRECTORY_NAME => 'DIR_EJEMPLO_ET1'
    );
END;
/
SELECT *
FROM DBMS_CLOUD.LIST_FILES('DIR_EJEMPLO_ET1')
ORDER BY OBJECT_NAME;
/
GRANT READ, WRITE ON DIRECTORY DIR_EJEMPLO_ET1 TO EJEMPLOPRUEBA3A;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_FOTOS_CLIENTES

IS
    CURSOR C_FOTO_CLIENTE IS
    SELECT NUMRUN,FOTO
    FROM CLIENTE
    ORDER BY 1;
    
    V_BFILE BFILE;
    V_SQLERRM VARCHAR2(250);
    
BEGIN
    
    FOR R_FOTO_CLIENTE IN C_FOTO_CLIENTE LOOP
        
        BEGIN
            V_BFILE := BFILENAME('DIR_EJEMPLO_ET1',R_FOTO_CLIENTE.NUMRUN||'.jpg');
            
            UPDATE CLIENTE
            SET FOTO = R_FOTO_CLIENTE.FOTO
            WHERE NUMRUN = R_FOTO_CLIENTE.NUMRUN;
            
            --CARGAR FOTO BFILE
            DBMS_LOB.OPEN(V_BFILE, DBMS_LOB.FILE_READONLY);        
            DBMS_LOB.LOADFROMFILE(R_FOTO_CLIENTE.FOTO,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));
            DBMS_LOB.CLOSE(V_BFILE);
                       
        EXCEPTION 
            WHEN OTHERS THEN
            V_SQLERRM := SQLERRM;
            INSERT INTO ERROR_COBRO_MENSUAL_TARJETA VALUES(SEQ_ERROR.NEXTVAL,'Error al insertar foto en cliente con numrun: '||R_FOTO_CLIENTE.NUMRUN,V_SQLERRM);
        
        END;

    END LOOP;
END SP_FOTOS_CLIENTES;

/

EXEC SP_FOTOS_CLIENTES;
/
SELECT * FROM CLIENTE
WHERE NUMRUN = 24617340;