/*TRIGGER*/
CREATE OR REPLACE TRIGGER TRG_FLRIP
AFTER INSERT ON TRANSACCION_TARJETA_CLIENTE
FOR EACH ROW
/*TRIGGER QUE ACTUALIZA LOS CUPOS DISPONIBLES DE COMPRA Y AVANCES AL MOMENTO DE HACER NUEVAS
TRANSACCIONES CON LA TARJETA*/
DECLARE
  
V_CUPO_DISP_COMPRA     TARJETA_CLIENTE.CUPO_DISP_COMPRA%TYPE;
V_CUPO_DISP_SP_AVANCE  TARJETA_CLIENTE.CUPO_DISP_SP_AVANCE%TYPE;

BEGIN
    IF :NEW.COD_TPTRAN_TARJETA = 101 OR :NEW.COD_TPTRAN_TARJETA = 102 THEN
    
        SELECT CUPO_DISP_COMPRA
        INTO V_CUPO_DISP_COMPRA
        FROM TARJETA_CLIENTE
        WHERE NRO_TARJETA = :NEW.NRO_TARJETA;
        
        UPDATE TARJETA_CLIENTE
        SET CUPO_DISP_COMPRA = V_CUPO_DISP_COMPRA - :NEW.MONTO_TOTAL_TRANSACCION
        WHERE NRO_TARJETA = :NEW.NRO_TARJETA;
        
    ELSIF :NEW.COD_TPTRAN_TARJETA = 103 THEN
        
        SELECT CUPO_DISP_SP_AVANCE
        INTO V_CUPO_DISP_SP_AVANCE
        FROM TARJETA_CLIENTE
        WHERE NRO_TARJETA = :NEW.NRO_TARJETA;
        
        UPDATE TARJETA_CLIENTE
        SET CUPO_DISP_SP_AVANCE = V_CUPO_DISP_SP_AVANCE - :NEW.MONTO_TOTAL_TRANSACCION
        WHERE NRO_TARJETA = :NEW.NRO_TARJETA;
    
    END IF;
    
END TRG_FLRIP;

/*INSERT*/
INSERT INTO TRANSACCION_TARJETA_CLIENTE VALUES(29320393064,1001,'25/03/17',900000,24,945000,101);
INSERT INTO TRANSACCION_TARJETA_CLIENTE VALUES(29320393064,1002,'04/04/18',76500,6,80325,101);
INSERT INTO TRANSACCION_TARJETA_CLIENTE VALUES(29320393064,1003,'25/04/18',585900,12,644490,103);
INSERT INTO TRANSACCION_TARJETA_CLIENTE VALUES(28418181488,1002,'05/02/18',300000,10,315000,102);
/
SELECT * FROM TRANSACCION_TARJETA_CLIENTE; --INSERT
SELECT * FROM TARJETA_CLIENTE
WHERE NRO_TARJETA = 29320393064 ; --UPDATE
